services:

 frontend:
  image: zelbanna/rims-frontend:latest
  ports:
   - 3000:3000/tcp
  restart: no
  volumes:
   - /usr/local/sbin/rims/react:/rims/src
   - /usr/local/sbin/rims/site:/rims/build
   - /usr/local/sbin/rims/static:/rims/public
  networks:
   infra_net:
    ipv4_address: 172.18.0.79

#Extra
networks:
 infra_net:
  external: true
