services:

 daemon:
  container_name: rims
  image: zelbanna/rims:latest
  ports:
   - 8079:8079/tcp
   - 8080:8080/tcp
  restart: unless-stopped
  volumes:
   - rims:/etc/rims/
   - /var/log/rims:/var/log/rims
  networks:
   infra_net:
    ipv4_address: 172.18.0.80

#Extra
networks:
 infra_net:
  external: true

volumes:
 rims:
  name: rims
