#!/usr/bin/python
# -*- coding: utf-8 -*-
__author__ = "Zacharias El Banna"
__version__ = "10.5GA"
__status__ = "Production"

from subprocess import call
from os import walk,path
from sys import argv, exit

for root,dirs,files in walk('.'):
 if ".git" in dirs:
  dirs.remove('.git')
 #print "Directory:",root
 for file in files:
  if file[-2:] == 'py':
   pfile = path.join(root,file)
   with open(pfile) as f:
    content = f.readlines()
    for line in content:
     if all(word in line for word in ["z-op","z-small-btn","images"]):
      print pfile,line.strip()
